task 0

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,11 +1,26 @@
 #!/usr/bin/env bash
-# the script transfers a file from our client to a server
-ARGS=4
-ERR_ARGS=1
-if [ "$#" -ne "$ARGS" ]
+# Checking for command-line argument
+if [ $# -lt 4 ]
 then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	exit "$ERR_ARGS"
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
-# Disable Strict host key checking
-scp -i "$4" -o "StrictHostKeyChecking=no" "$1" "$3"@"$2":~\
+
+# Assigning Arguments to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+
+# Disabbling Strict Host Key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# Checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+  echo "FILE TRANSFER WAS SUCCESSFULL"
+else
+  echo "FILE TRANSFER FAILED"
+fi
